services:
  transactions.api.left:
    image: transactions.api
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=localhost
      - ConnectionStrings__postgres=Host=db;Port=5432;Database=transactions;Username=postgres;Password=postgres
    depends_on:
      - db
  
  transactions.api.right:
    image: transactions.api    
    ports:
      - "6000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=localhost
      - ConnectionStrings__postgres=Host=db;Port=5432;Database=transactions;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: